/* eslint-disable react-refresh/only-export-components */
import { createContext, useCallback, useContext, useEffect, useState } from 'react';

export const translations = {
  'meta.title': { es: 'SERLIMCA | Soluciones industriales', en: 'SERLIMCA | Industrial solutions', cn: 'SERLIMCA | 工业解决方案' },
  'brand.logo': { es: 'Logotipo de SERLIMCA', en: 'SERLIMCA logo', cn: 'SERLIMCA 标志' },
  'nav.home': { es: 'Inicio', en: 'Home', cn: '首页' },
  'nav.about': { es: 'Nosotros', en: 'About', cn: '关于我们' },
  'nav.services': { es: 'Servicios', en: 'Services', cn: '服务项目' },
  'nav.coverage': { es: 'Cobertura', en: 'Coverage', cn: '服务覆盖' },
  'nav.gallery': { es: 'Galería', en: 'Gallery', cn: '项目图库' },
  'nav.contact': { es: 'Contáctanos', en: 'Contact us', cn: '联系我们' },
  'nav.openMenu': { es: 'Abrir menú', en: 'Open menu', cn: '打开菜单' },
  'nav.closeMenu': { es: 'Cerrar menú', en: 'Close menu', cn: '关闭菜单' },
  'language.selector': { es: 'Seleccionar idioma', en: 'Select language', cn: '选择语言' },

  'hero.title': { es: 'Soluciones integrales', en: 'Comprehensive solutions', cn: '全方位解决方案' },
  'hero.subtitle': { es: 'para el Sector Petrolero', en: 'for the Oil Sector', cn: '专为石油行业打造' },
  'hero.description': { es: 'Servicios de izamiento y transporte de carga pesada con altos estándares de seguridad y calidad.', en: 'Heavy cargo lifting and transportation services delivered to high safety and quality standards.', cn: '提供重型货物吊装与运输服务，遵循高标准的安全与质量要求。' },
  'hero.cta.quote': { es: 'Solicitar cotización', en: 'Request a quote', cn: '获取报价' },
  'hero.cta.services': { es: 'Nuestros servicios', en: 'Our services', cn: '我们的服务' },

  'about.title': { es: 'Sobre nosotros', en: 'About us', cn: '关于我们' },
  'about.subtitle': { es: 'Nuestro camino al éxito', en: 'Our journey to success', cn: '我们的成功之路' },
  'about.description': { es: 'En SERLIMCA somos especialistas en izamiento y transporte de carga pesada, respaldados por una infraestructura sólida y un equipo experto en logística, mantenimiento y seguridad. Nos distinguimos por trabajar con altos estándares de calidad, capacidad operativa y control riguroso en cada etapa del proceso.', en: 'At SERLIMCA, we specialize in heavy cargo lifting and transportation, supported by solid infrastructure and an expert team in logistics, maintenance, and safety. We stand out for high quality standards, operational capacity, and rigorous control at every stage.', cn: 'SERLIMCA 专注于重型货物吊装与运输，拥有完善的基础设施以及物流、维护和安全领域的专业团队。我们以高质量标准、卓越运营能力以及对每个环节的严格控制而著称。' },
  'about.shortdescription': { es: 'Nuestro compromiso es brindar soluciones eficientes y seguras de izamiento y transporte de carga pesada, garantizando que cada activo llegue a su destino con la puntualidad y la integridad que exige el sector industrial.', en: 'Our commitment is to provide efficient, safe heavy cargo lifting and transportation solutions, ensuring every asset reaches its destination with the punctuality and integrity required by the industrial sector.', cn: '我们致力于提供高效、安全的重型货物吊装与运输解决方案，确保每项资产以工业领域所需的准时性和完整性到达目的地。' },
  'about.cta.learnmore': { es: 'Conoce más sobre nosotros', en: 'Learn more about us', cn: '了解更多关于我们' },
  'about.values.eyebrow': { es: 'Nuestros valores', en: 'Our values', cn: '我们的价值观' },
  'about.values.title': { es: 'Principios que guían cada operación', en: 'Principles that guide every operation', cn: '指导每项作业的原则' },
  'about.values.description': { es: 'Estos valores sostienen nuestra cultura de trabajo y la forma en que asumimos cada servicio dentro del sector petrolero e industrial.', en: 'These values support our work culture and how we approach every service in the oil and industrial sectors.', cn: '这些价值观支撑着我们的工作文化，并指导我们在石油和工业领域开展每项服务。' },
  'about.values.honesty.title': { es: 'Honestidad', en: 'Integrity', cn: '诚信' },
  'about.values.honesty.description': { es: 'Actuamos con transparencia y coherencia en cada relación comercial y operativa.', en: 'We act with transparency and consistency in every commercial and operational relationship.', cn: '我们在每一项商业和运营关系中坚持透明与一致。' },
  'about.values.quality.title': { es: 'Calidad', en: 'Quality', cn: '质量' },
  'about.values.quality.description': { es: 'Cuidamos cada detalle técnico para entregar servicios confiables y bien ejecutados.', en: 'We take care of every technical detail to deliver reliable, well-executed services.', cn: '我们关注每个技术细节，提供可靠且执行到位的服务。' },
  'about.values.punctuality.title': { es: 'Puntualidad', en: 'Punctuality', cn: '准时' },
  'about.values.punctuality.description': { es: 'Respetamos los tiempos acordados y planificamos cada operación con precisión.', en: 'We honor agreed schedules and plan every operation precisely.', cn: '我们遵守约定时间，并精准规划每项作业。' },
  'about.values.passion.title': { es: 'Pasión', en: 'Passion', cn: '热情' },
  'about.values.passion.description': { es: 'Trabajamos con compromiso, energía y orgullo por lo que hacemos.', en: 'We work with commitment, energy, and pride in what we do.', cn: '我们以责任感、活力和自豪感投入工作。' },
  'about.values.competitiveness.title': { es: 'Competitividad', en: 'Competitiveness', cn: '竞争力' },
  'about.values.competitiveness.description': { es: 'Mejoramos continuamente para responder con eficiencia a las exigencias del sector.', en: 'We continuously improve to respond efficiently to the sector’s demands.', cn: '我们持续改进，以高效回应行业需求。' },
  'about.values.teamwork.title': { es: 'Trabajo en equipo', en: 'Teamwork', cn: '团队协作' },
  'about.values.teamwork.description': { es: 'Integramos experiencia, comunicación y coordinación para alcanzar objetivos comunes.', en: 'We combine experience, communication, and coordination to achieve common goals.', cn: '我们融合经验、沟通和协调，共同实现目标。' },
  'about.values.customerOrientation.title': { es: 'Orientación al cliente', en: 'Customer focus', cn: '客户导向' },
  'about.values.customerOrientation.description': { es: 'Escuchamos cada requerimiento y desarrollamos soluciones ajustadas a sus necesidades.', en: 'We listen to every requirement and develop solutions tailored to each client’s needs.', cn: '我们倾听每项需求，并制定符合客户需要的解决方案。' },
  'about.values.socialResponsibility.title': { es: 'Responsabilidad social', en: 'Social responsibility', cn: '社会责任' },
  'about.values.socialResponsibility.description': { es: 'Promovemos operaciones responsables con nuestro personal, clientes, comunidad y entorno.', en: 'We promote responsible operations with our people, clients, community, and environment.', cn: '我们推动对员工、客户、社区和环境负责的运营方式。' },
  'about.values.problemSolving.title': { es: 'Resolución de problemas', en: 'Problem solving', cn: '解决问题' },
  'about.values.problemSolving.description': { es: 'Respondemos con criterio técnico y agilidad ante los retos de cada operación.', en: 'We respond to every operational challenge with technical judgment and agility.', cn: '面对每项作业挑战，我们以专业判断和敏捷响应解决问题。' },
  'about.page.hero.eyebrow': { es: 'Liderazgo en ingeniería de mantenimiento', en: 'Leadership in maintenance engineering', cn: '维护工程领域的领导力' },
  'about.page.hero.title': { es: 'Excelencia operativa en el', en: 'Operational excellence in the', cn: '卓越运营，服务于' },
  'about.page.hero.highlight': { es: 'Sector Petrolero', en: 'Oil Industry', cn: '石油行业' },
  'about.page.intro.eyebrow': { es: 'Nuestra organización', en: 'Our organization', cn: '我们的组织' },
  'about.page.intro.title': { es: 'Quiénes somos', en: 'Who we are', cn: '我们是谁' },
  'about.page.intro.beforeCompany': { es: 'Somos', en: 'We are', cn: '我们是' },
  'about.page.intro.afterCompany': { es: 'una compañía especializada en el soporte técnico, el mantenimiento y la reparación de infraestructura crítica del sector petrolero. Fue fundada en', en: 'a company specializing in technical support, maintenance, and repair of critical oil-industry infrastructure. We were founded in', cn: '一家专注于石油行业关键基础设施技术支持、维护和维修的公司。公司成立于' },
  'about.page.intro.location': { es: 'El Tigre, estado Anzoátegui', en: 'El Tigre, Anzoátegui State', cn: '安索阿特吉州埃尔蒂格雷' },
  'about.page.intro.beforeYear': { es: 'en el año', en: 'in', cn: '，时间为' },
  'about.page.intro.quality': { es: 'Aseguramos que cada intervención cumpla con los estándares internacionales de calidad y seguridad industrial más exigentes.', en: 'We ensure every intervention meets the most demanding international quality and industrial safety standards.', cn: '我们确保每项作业均符合最严格的国际质量和工业安全标准。' },
  'about.page.experience': { es: 'Años de experiencia técnica', en: 'Years of technical experience', cn: '年技术经验' },
  'about.page.mission.title': { es: 'Misión', en: 'Mission', cn: '使命' },
  'about.page.mission.description': { es: 'Prestar servicios a la industria petrolera, priorizando la seguridad y la rentabilidad para garantizar la satisfacción de nuestros clientes.', en: 'To serve the oil industry while prioritizing safety and profitability to ensure customer satisfaction.', cn: '为石油行业提供服务，以安全和盈利能力为重点，确保客户满意。' },
  'about.page.vision.title': { es: 'Visión', en: 'Vision', cn: '愿景' },
  'about.page.vision.description': { es: 'Posicionarnos como la compañía más confiable en izamiento y transporte de carga pesada a nivel nacional.', en: 'To become the country’s most trusted company for heavy cargo lifting and transportation nationwide.', cn: '成为全国最值得信赖的重型货物吊装与运输服务公司。' },
  'about.page.goals.title': { es: 'Nuestros objetivos', en: 'Our objectives', cn: '我们的目标' },
  'about.page.goals.strategic.title': { es: 'Estratégicos', en: 'Strategic', cn: '战略目标' },
  'about.page.goals.strategic.description': { es: 'Ser un referente nacional en nuestra especialidad, fortaleciendo las relaciones comerciales con nuestros clientes leales y confiables, garantizándoles un trato especial y preferencial.', en: 'To become a national benchmark in our specialty by strengthening relationships with loyal, trusted clients and providing attentive, preferential service.', cn: '成为本专业领域的全国标杆，加强与忠诚且值得信赖的客户之间的商业关系，并提供周到、优先的服务。' },
  'about.page.goals.operational.title': { es: 'Operacional', en: 'Operational', cn: '运营目标' },
  'about.page.goals.operational.description': { es: 'Diversificar los servicios prestados a la industria petrolera. Los nuevos servicios deberán priorizar los factores tecnológico y técnico.', en: 'To diversify the services provided to the oil industry, prioritizing technological and technical factors in each new service.', cn: '实现石油行业服务多元化，并在每项新服务中优先考虑技术与专业因素。' },
  'about.page.goals.tactical.title': { es: 'Táctico', en: 'Tactical', cn: '战术目标' },
  'about.page.goals.tactical.description': { es: 'Conseguir clientes afines a nuestros valores con los cuales establecer relaciones comerciales estrechas y rentables.', en: 'To attract clients who share our values and establish close, profitable business relationships.', cn: '吸引认同我们价值观的客户，并与其建立紧密、互利的商业关系。' },
  'about.page.cta.title': { es: 'Potencie su capacidad operativa hoy mismo', en: 'Strengthen your operational capacity today', cn: '立即提升您的运营能力' },
  'about.page.cta.button': { es: 'Solicitar consultoría técnica', en: 'Request technical consulting', cn: '申请技术咨询' },

  'services.title': { es: 'Servicios', en: 'Services', cn: '服务项目' },
  'services.subtitle': { es: 'Nuestras soluciones', en: 'Our solutions', cn: '我们的解决方案' },
  'services.liftingTransport.title': { es: 'Izamiento y transporte de carga pesada', en: 'Heavy cargo lifting and transportation', cn: '重型货物吊装与运输' },
  'services.liftingTransport.description': { es: 'Ejecutamos servicios integrales de izamiento y transporte de carga pesada, incluyendo carga, traslado y descarga con equipos de alta capacidad y personal especializado, garantizando una operación segura y eficiente.', en: 'We deliver comprehensive heavy cargo lifting and transportation services, including loading, transfer, and unloading with high-capacity equipment and specialized personnel, ensuring safe and efficient operations.', cn: '我们提供一体化重型货物吊装与运输服务，包括使用大吨位设备和专业人员进行装载、转运和卸载，确保作业安全高效。' },
  'services.maintenance.title': { es: 'Mantenimiento y reparación de balancines y Rotaflex', en: 'Pumping unit and Rotaflex maintenance and repair', cn: '游梁式抽油机与 Rotaflex 设备维护及维修' },
  'services.maintenance.description': { es: 'Realizamos mantenimiento preventivo, correctivo, inspección, diagnóstico y reparación de equipos de bombeo mecánico (balancines y rotaflex) para preservar su confiabilidad, rendimiento y continuidad operativa.', en: 'We provide preventive and corrective maintenance, inspection, diagnostics, and repair of mechanical pumping equipment (pumpjacks and Rotaflex) to preserve reliability, performance, and operational continuity.', cn: '我们为机械采油设备（游梁式抽油机和 Rotaflex）提供预防性及纠正性维护、检查、诊断与维修，保障设备的可靠性、性能和持续运行。' },
  'services.rigMoving.title': { es: 'Mudanza de taladros de perforación, cabilleros y workover', en: 'Drilling, rod service, and workover rig moving', cn: '钻井、抽油杆作业及修井设备搬迁' },
  'services.rigMoving.description': { es: 'Planificamos y ejecutamos la movilización de taladros y equipos asociados mediante izamiento y transporte de carga pesada, coordinando desmontaje, carga, descarga y posicionamiento con estricto control operativo y de seguridad.', en: 'We plan and execute the relocation of rigs and associated equipment through heavy cargo lifting and transportation, coordinating disassembly, loading, unloading, and positioning under strict operational and safety controls.', cn: '我们通过重型货物吊装与运输规划并执行钻机及配套设备搬迁，协调拆卸、装载、卸载和定位全过程，并严格落实作业与安全管控。' },
  'services.logistics.title': { es: 'Logística para izamiento y transporte de carga pesada', en: 'Logistics for heavy cargo lifting and transportation', cn: '重型货物吊装与运输物流' },
  'services.logistics.description': { es: 'Coordinamos rutas, recursos, tiempos de entrega y seguimiento para cada operación de izamiento y transporte de carga pesada, asegurando que sus activos lleguen a destino de forma puntual y segura.', en: 'We coordinate routes, resources, delivery schedules, and tracking for every heavy cargo lifting and transportation operation, ensuring assets arrive safely and on time.', cn: '我们为每项重型货物吊装与运输作业统筹路线、资源、交付时间和追踪，确保资产安全、准时到达目的地。' },
  'services.question': { es: '¿Listo para optimizar su infraestructura?', en: 'Ready to optimize your infrastructure?', cn: '准备好优化您的基础设施了吗？' },
  'services.cta.button': { es: 'Explorar todas las capacidades técnicas', en: 'Explore all technical capabilities', cn: '探索所有技术能力' },
  'services.page.eyebrow': { es: 'Capacidades técnicas', en: 'Technical capabilities', cn: '技术能力' },
  'services.page.title': { es: 'Soluciones de ingeniería para la industria energética', en: 'Engineering solutions for the energy industry', cn: '面向能源行业的工程解决方案' },
  'services.page.consultTitle': { es: 'Inicie una consulta técnica', en: 'Start a technical consultation', cn: '开始技术咨询' },
  'services.page.consultDescription': { es: 'Nuestro equipo de ingeniería está disponible para realizar levantamientos técnicos y proponer soluciones a medida para su operación.', en: 'Our engineering team is available to conduct technical assessments and propose tailored solutions for your operation.', cn: '我们的工程团队可提供技术评估，并为您的运营提出定制化解决方案。' },
  'services.page.consultButton': { es: 'Programar evaluación técnica', en: 'Schedule a technical assessment', cn: '预约技术评估' },
  'services.page.footer': { es: 'Operaciones de alta integridad', en: 'High-integrity operations', cn: '高完整性运营' },
  'services.page.assetLogistics.title': { es: 'Izamiento y transporte de carga pesada', en: 'Heavy cargo lifting and transportation', cn: '重型货物吊装与运输' },
  'services.page.assetLogistics.description': { es: 'Servicios integrales de izamiento y transporte de carga pesada para infraestructura energética. Especializados en el traslado de componentes de perforación y equipos de alta precisión bajo normativas internacionales de seguridad.', en: 'Comprehensive heavy cargo lifting and transportation services for energy infrastructure. We specialize in moving drilling components and high-precision equipment under international safety standards.', cn: '为能源基础设施提供一体化重型货物吊装与运输服务。我们专注于在国际安全标准下转运钻井部件和高精度设备。' },
  'services.page.assetLogistics.details': { es: ['Unidades certificadas para izamiento y transporte de carga pesada', 'Sistemas avanzados de telemetría y monitoreo 24/7', 'Protocolos HSE integrados', 'Gestión documental y permisos de tránsito especial'], en: ['Certified units for heavy cargo lifting and transportation', 'Advanced telemetry and 24/7 monitoring systems', 'Integrated HSE protocols', 'Documentation management and special transit permits'], cn: ['重型货物吊装与运输认证设备', '先进的遥测和全天候监控系统', '集成 HSE 协议', '文件管理和特殊通行许可'] },
  'services.page.maintenance.title': { es: 'Ingeniería de mantenimiento integral', en: 'Comprehensive maintenance engineering', cn: '综合维护工程' },
  'services.page.maintenance.description': { es: 'Programas técnicos diseñados para maximizar la vida útil de los activos. Aplicamos metodologías de mantenimiento basado en la condición para reducir el tiempo de inactividad no programado.', en: 'Technical programs designed to maximize asset life. We apply condition-based maintenance methodologies to reduce unplanned downtime.', cn: '旨在最大化资产使用寿命的技术方案。我们采用基于状态的维护方法，减少非计划停机时间。' },
  'services.page.maintenance.details': { es: ['Diagnóstico por análisis de vibraciones y termografía', 'Mantenimiento preventivo de sistemas de bombeo', 'Optimización de rendimiento de maquinaria rotativa', 'Auditorías técnicas de integridad mecánica'], en: ['Diagnostics through vibration analysis and thermography', 'Preventive maintenance for pumping systems', 'Rotating machinery performance optimization', 'Mechanical integrity technical audits'], cn: ['振动分析和热成像诊断', '泵送系统预防性维护', '旋转机械性能优化', '机械完整性技术审计'] },
  'services.page.fieldSupport.title': { es: 'Soporte de campo y reparación especializada', en: 'Field support and specialized repair', cn: '现场支持与专业维修' },
  'services.page.fieldSupport.description': { es: 'Capacidad de respuesta técnica inmediata para la restauración funcional de activos críticos en sitio, asegurando el retorno a la operación en tiempos mínimos.', en: 'Immediate technical response capability to restore critical assets on-site, ensuring a return to operation in the shortest possible time.', cn: '可快速响应并在现场恢复关键资产功能，确保在最短时间内恢复运营。' },
  'services.page.fieldSupport.details': { es: ['Especialistas senior certificados en API / ISO', 'Suministro de componentes de grado industrial', 'Pruebas hidrostáticas y de hermeticidad posteriores a la reparación', 'Servicio de respuesta para contingencias 24/7'], en: ['Senior specialists certified in API / ISO', 'Industrial-grade component supply', 'Post-repair hydrostatic and leak tests', '24/7 contingency response service'], cn: ['通过 API / ISO 认证的高级专家', '工业级部件供应', '维修后的水压和密封测试', '全天候应急响应服务'] },

  'why.experience': { es: '+23 años de experiencia', en: '+23 years of experience', cn: '23 多年经验' },
  'why.certification': { es: 'Certificación', en: 'Certification', cn: '认证' },
  'why.quality': { es: 'Calidad garantizada', en: 'Quality guaranteed', cn: '质量保证' },
  'why.cta.years': { es: 'años de trayectoria', en: 'years of experience', cn: '年行业经验' },
  'why.cta.projects': { es: 'proyectos exitosos', en: 'successful projects', cn: '成功项目' },
  'why.cta.experts': { es: 'expertos certificados', en: 'certified experts', cn: '认证专家' },
  'why.cta.support': { es: 'aliados estratégicos', en: 'strategic partners', cn: '战略合作伙伴' },
  'quick.years': { es: 'años', en: 'years', cn: '年' },
  'quick.projects': { es: 'proyectos', en: 'projects', cn: '项目' },
  'quick.support': { es: 'soporte', en: 'support', cn: '支持' },

  'coverage.eyebrow': { es: 'Presencia estratégica', en: 'Strategic presence', cn: '战略布局' },
  'coverage.title': { es: 'Cobertura', en: 'Coverage', cn: '服务覆盖' },
  'coverage.highlight': { es: 'nacional', en: 'nationwide', cn: '全国' },
  'coverage.description': { es: 'Desplegamos soluciones logísticas e industriales en los nodos operativos más importantes de Venezuela, garantizando respuesta inmediata.', en: 'We deploy logistics and industrial solutions across Venezuela’s most important operational hubs, ensuring an immediate response.', cn: '我们在委内瑞拉最重要的运营节点部署物流和工业解决方案，确保快速响应。' },
  'coverage.mapAlt': { es: 'Mapa de cobertura de Venezuela', en: 'Venezuela coverage map', cn: '委内瑞拉服务覆盖地图' },
  'coverage.badge': { es: '100% operativo', en: '100% operational', cn: '100% 运营中' },

  'gallery.eyebrow': { es: 'Experiencia en campo', en: 'Field experience', cn: '现场经验' },
  'gallery.title': { es: 'Operaciones que hablan por nosotros', en: 'Operations that speak for us', cn: '让成果为我们代言' },
  'gallery.description': { es: 'Una mirada a nuestro equipo, capacidad técnica y ejecución de maniobras industriales en condiciones reales.', en: 'A look at our team, technical capability, and execution of industrial operations in real conditions.', cn: '带您了解我们的团队、技术能力以及在真实条件下执行工业作业的成果。' },
  'gallery.category.all': { es: 'Todos', en: 'All', cn: '全部' },
  'gallery.category.lifting': { es: 'Izamiento', en: 'Lifting', cn: '吊装' },
  'gallery.category.transport': { es: 'Izamiento y transporte de carga pesada', en: 'Heavy cargo lifting and transportation', cn: '重型货物吊装与运输' },
  'gallery.category.maintenance': { es: 'Mantenimiento', en: 'Maintenance', cn: '维护' },
  'gallery.category.equipment': { es: 'Equipos', en: 'Equipment', cn: '设备' },
  'gallery.expandImage': { es: 'Ampliar imagen: {{title}}', en: 'Expand image: {{title}}', cn: '放大图片：{{title}}' },
  'gallery.close': { es: 'Cerrar galería', en: 'Close gallery', cn: '关闭图库' },
  'gallery.previous': { es: 'Imagen anterior', en: 'Previous image', cn: '上一张图片' },
  'gallery.next': { es: 'Imagen siguiente', en: 'Next image', cn: '下一张图片' },
  'gallery.image.1.title': { es: 'Operación de izamiento coordinado', en: 'Coordinated lifting operation', cn: '协同吊装作业' },
  'gallery.image.1.description': { es: 'Maniobra ejecutada con equipos de alta capacidad y control operativo en campo.', en: 'Operation performed with high-capacity equipment and field operational control.', cn: '使用大吨位设备并实施现场作业控制完成的作业。' },
  'gallery.image.2.title': { es: 'Izamiento y transporte de carga pesada con grúa telescópica', en: 'Heavy cargo lifting and transportation with a telescopic crane', cn: '使用伸缩臂起重机进行重型货物吊装与运输' },
  'gallery.image.2.description': { es: 'Movilización segura de maquinaria pesada sobre unidad de cama baja.', en: 'Safe movement of heavy machinery on a low-bed trailer.', cn: '通过低平板拖车安全运输重型机械。' },
  'gallery.image.3.title': { es: 'Manejo de componentes industriales', en: 'Industrial component handling', cn: '工业部件搬运' },
  'gallery.image.3.description': { es: 'Recepción y manipulación controlada de componentes para operaciones técnicas.', en: 'Controlled receipt and handling of components for technical operations.', cn: '为技术作业进行受控的部件接收和搬运。' },
  'gallery.image.4.title': { es: 'Izamiento de equipo petrolero', en: 'Oil equipment lifting', cn: '石油设备吊装' },
  'gallery.image.4.description': { es: 'Posicionamiento de activos industriales mediante grúa telescópica.', en: 'Positioning of industrial assets using a telescopic crane.', cn: '使用伸缩臂起重机定位工业资产。' },
  'gallery.image.5.title': { es: 'Grúa de alta capacidad', en: 'High-capacity crane', cn: '大吨位起重机' },
  'gallery.image.5.description': { es: 'Inspección y preparación operativa de equipos especializados.', en: 'Inspection and operational preparation of specialized equipment.', cn: '对专业设备进行检查和作业准备。' },
  'gallery.image.6.title': { es: 'Trabajo técnico en altura', en: 'Technical work at height', cn: '高空技术作业' },
  'gallery.image.6.description': { es: 'Intervención con brazos hidráulicos y personal especializado.', en: 'Intervention with hydraulic booms and specialized personnel.', cn: '由专业人员使用液压臂进行作业。' },
  'gallery.image.7.title': { es: 'Movilización de maquinaria', en: 'Machinery mobilization', cn: '机械设备调动' },
  'gallery.image.7.description': { es: 'Despliegue planificado de grúa para operaciones de izamiento y transporte de carga pesada en campo.', en: 'Planned crane deployment for heavy cargo lifting and transportation operations in the field.', cn: '为现场重型货物吊装与运输作业进行规划的起重机部署。' },
  'gallery.image.8.title': { es: 'Flota de equipos especializados', en: 'Specialized equipment fleet', cn: '专业设备车队' },
  'gallery.image.8.description': { es: 'Unidades disponibles para operaciones industriales de alta exigencia.', en: 'Units available for demanding industrial operations.', cn: '可用于高要求工业作业的设备。' },

  'about.corporate.hero.eyebrow': { es: 'Perfil corporativo', en: 'Corporate profile', cn: '企业概览' },
  'about.corporate.hero.title': { es: 'Precisión y Escala Industrial en Servicios Petroleros', en: 'Precision and Industrial Scale in Oilfield Services', cn: '石油服务中的精准与工业规模' },
  'about.corporate.hero.description': { es: 'Capacidades operativas y logísticas para responder con seguridad, calidad y disciplina técnica a los desafíos del sector.', en: 'Operational and logistics capabilities that meet the sector’s challenges with safety, quality, and technical discipline.', cn: '以安全、质量和技术规范应对行业挑战的运营与物流能力。' },

  'about.corporate.evolution.eyebrow': { es: 'Nuestra evolución', en: 'Our evolution', cn: '我们的发展历程' },
  'about.corporate.evolution.title': { es: 'Trayectoria construida desde 2003', en: 'A track record built since 2003', cn: '自 2003 年以来积淀的行业经验' },
  'about.corporate.evolution.description': { es: 'SERLIMCA nació en El Tigre, estado Anzoátegui, y evolucionó desde servicios operativos iniciales para el sector petrolero hasta un portafolio especializado de izamiento y transporte de carga pesada, mantenimiento y movilización técnica.', en: 'SERLIMCA was founded in El Tigre, Anzoátegui State, and evolved from early operational services for the oil sector into a specialized portfolio of heavy cargo lifting and transportation, maintenance, and technical mobilization.', cn: 'SERLIMCA 创立于安索阿特吉州埃尔蒂格雷，已从石油行业的早期运营服务发展为涵盖重型货物吊装与运输、维护和技术调动的专业服务组合。' },
  'about.corporate.evolution.marker': { es: '01', en: '01', cn: '01' },
  'about.corporate.evolution.origin.year': { es: '2003', en: '2003', cn: '2003 年' },
  'about.corporate.evolution.origin.title': { es: 'Origen: El Tigre, Anzoátegui', en: 'Origin: El Tigre, Anzoátegui', cn: '起源：安索阿特吉州埃尔蒂格雷' },
  'about.corporate.evolution.origin.description': { es: 'Fundada para responder a necesidades operativas críticas en taladros de perforación.', en: 'Founded to respond to critical operational needs on drilling rigs.', cn: '成立之初旨在满足钻井平台的关键运营需求。' },
  'about.corporate.evolution.capacity.year': { es: 'Actualidad', en: 'Today', cn: '如今' },
  'about.corporate.evolution.capacity.title': { es: 'Capacidad actual: izamiento y transporte de carga pesada', en: 'Current capability: heavy cargo lifting and transportation', cn: '当前能力：重型货物吊装与运输' },
  'about.corporate.evolution.capacity.description': { es: 'Portafolio especializado impulsado por tecnología, maquinaria pesada de alta capacidad y un equipo técnico calificado.', en: 'A specialized portfolio powered by technology, high-capacity heavy equipment, and a qualified technical team.', cn: '依托技术、高能力重型设备和专业技术团队打造的专业服务组合。' },

  'about.corporate.dna.eyebrow': { es: 'ADN corporativo', en: 'Corporate DNA', cn: '企业基因' },
  'about.corporate.dna.title': { es: 'Una organización orientada a la ejecución confiable', en: 'An organization built for reliable execution', cn: '以可靠执行为核心的组织' },
  'about.corporate.dna.description': { es: 'Integramos experiencia en campo, capacidad técnica y una cultura de seguridad para respaldar operaciones exigentes.', en: 'We combine field experience, technical capacity, and a safety culture to support demanding operations.', cn: '我们将现场经验、技术能力和安全文化相结合，为高要求作业提供支持。' },
  'about.corporate.dna.vision.label': { es: 'Visión', en: 'Vision', cn: '愿景' },
  'about.corporate.dna.vision.title': { es: 'Ser la mejor compañía de servicios petroleros a nivel nacional.', en: 'To be the leading oilfield services company nationwide.', cn: '成为全国领先的石油服务公司。' },
  'about.corporate.dna.vision.description': { es: 'Trabajamos para ser un referente por capacidad operativa, confiabilidad y respuesta técnica.', en: 'We work to become a benchmark for operational capacity, reliability, and technical response.', cn: '我们致力于在运营能力、可靠性和技术响应方面成为行业标杆。' },
  'about.corporate.dna.mission.label': { es: 'Misión', en: 'Mission', cn: '使命' },
  'about.corporate.dna.mission.title': { es: 'Servicios rentables, seguros y de alta calidad.', en: 'Profitable, safe, high-quality services.', cn: '高效益、安全、高质量的服务。' },
  'about.corporate.dna.mission.description': { es: 'Prestar servicios a la industria petrolera con estándares exigentes de calidad y seguridad, precios competitivos y foco en la satisfacción de nuestros clientes.', en: 'To serve the oil industry with demanding quality and safety standards, competitive pricing, and a focus on customer satisfaction.', cn: '为石油行业提供服务，遵循严格的质量与安全标准，提供有竞争力的价格，并以客户满意度为重点。' },

  'about.corporate.values.eyebrow': { es: 'El eje de nuestro trabajo', en: 'The core of our work', cn: '我们工作的核心' },
  'about.corporate.values.title': { es: 'Valores que orientan cada operación', en: 'Values that guide every operation', cn: '指导每项作业的价值观' },
  'about.corporate.values.description': { es: 'Nuestra cultura traduce principios corporativos en decisiones concretas de servicio, seguridad y colaboración.', en: 'Our culture translates corporate principles into concrete service, safety, and collaboration decisions.', cn: '我们的文化将企业原则转化为服务、安全和协作方面的具体决策。' },

  'about.corporate.pillars.eyebrow': { es: 'Portafolio de servicios petroleros', en: 'Oilfield services portfolio', cn: '石油服务组合' },
  'about.corporate.pillars.title': { es: 'Tres pilares para la continuidad operativa', en: 'Three pillars for operational continuity', cn: '保障运营连续性的三大支柱' },
  'about.corporate.pillars.description': { es: 'Servicios complementarios para movilizar, mantener y respaldar activos críticos de la operación petrolera.', en: 'Complementary services to mobilize, maintain, and support critical oilfield assets.', cn: '用于调动、维护和支持石油作业关键资产的配套服务。' },
  'about.corporate.pillars.label': { es: 'Pilar {{number}}', en: 'Pillar {{number}}', cn: '支柱 {{number}}' },
  'about.corporate.pillars.lifting.title': { es: 'Izamiento y transporte de carga pesada', en: 'Heavy cargo lifting and transportation', cn: '重型货物吊装与运输' },
  'about.corporate.pillars.lifting.description': { es: 'Servicios de izamiento y transporte de carga pesada para infraestructura crítica, con planificación técnica y soporte logístico en campo.', en: 'Heavy cargo lifting and transportation services for critical infrastructure, with technical planning and field logistics support.', cn: '为关键基础设施提供重型货物吊装与运输服务，配备技术规划和现场物流支持。' },
  'about.corporate.pillars.lifting.point1': { es: 'Maniobras de alta precisión respaldadas por operadores certificados.', en: 'High-precision maneuvers supported by certified operators.', cn: '由认证操作员支持的高精度作业。' },
  'about.corporate.pillars.lifting.point2': { es: 'Capacidad para el izamiento y transporte de carga pesada en infraestructura crítica.', en: 'Capability to support heavy cargo lifting and transportation for critical infrastructure.', cn: '具备关键基础设施重型货物吊装与运输作业能力。' },
  'about.corporate.pillars.lifting.point3': { es: 'Logística integrada para izamiento y transporte de carga pesada en campo.', en: 'Integrated logistics for heavy cargo lifting and transportation in the field.', cn: '为现场重型货物吊装与运输提供一体化物流支持。' },
  'about.corporate.pillars.maintenance.title': { es: 'Mantenimiento especializado', en: 'Specialized maintenance', cn: '专业维护' },
  'about.corporate.pillars.maintenance.description': { es: 'Mantenimiento y reparación de balancines y Rotaflex para contribuir a la continuidad de la producción.', en: 'Maintenance and repair of pumpjacks and Rotaflex units to support production continuity.', cn: '提供抽油机和 Rotaflex 装置的维护与维修服务，助力生产连续性。' },
  'about.corporate.pillars.maintenance.point1': { es: 'Diagnóstico y reparación de unidades de bombeo mecánico.', en: 'Diagnosis and repair of mechanical pumping units.', cn: '机械抽油装置的诊断与维修。' },
  'about.corporate.pillars.maintenance.point2': { es: 'Minimización de tiempos de inactividad en pozos productivos.', en: 'Downtime reduction in producing wells.', cn: '减少生产井的停机时间。' },
  'about.corporate.pillars.maintenance.point3': { es: 'Intervenciones preventivas y correctivas de alta calidad.', en: 'High-quality preventive and corrective interventions.', cn: '高质量的预防性和纠正性作业。' },
  'about.corporate.pillars.moving.title': { es: 'Mudanza de equipos', en: 'Equipment relocation', cn: '设备搬迁' },
  'about.corporate.pillars.moving.description': { es: 'Gestión logística para la movilización segura y eficiente de taladros y estructuras de gran envergadura.', en: 'Logistics management for the safe, efficient mobilization of rigs and large-scale structures.', cn: '为钻机和大型结构提供安全、高效调动的物流管理。' },
  'about.corporate.pillars.moving.point1': { es: 'Movilización de equipos de perforación, workover y cabilleros.', en: 'Mobilization of drilling, workover, and wireline equipment.', cn: '钻井、修井和测井设备的调动。' },
  'about.corporate.pillars.moving.point2': { es: 'Planificación de rutas y aseguramiento de carga.', en: 'Route planning and cargo securing.', cn: '路线规划与货物固定。' },
  'about.corporate.pillars.moving.point3': { es: 'Escolta operativa y coordinación para el traslado nacional.', en: 'Operational escort and coordination for nationwide transport.', cn: '全国运输的运营护送与协调。' },

  'about.corporate.capacity.eyebrow': { es: 'Capacidad operativa', en: 'Operational capacity', cn: '运营能力' },
  'about.corporate.capacity.title': { es: 'Recursos preparados para operaciones complejas', en: 'Resources prepared for complex operations', cn: '为复杂作业做好准备的资源' },
  'about.corporate.capacity.description': { es: 'La capacidad de SERLIMCA se apoya en equipos especializados, despliegue técnico y prácticas de prevención de riesgos.', en: 'SERLIMCA’s capability is supported by specialized equipment, technical deployment, and risk-prevention practices.', cn: 'SERLIMCA 的能力由专业设备、技术部署和风险预防实践提供支持。' },
  'about.corporate.capacity.lifting.title': { es: 'Izamiento y transporte de carga pesada', en: 'Heavy cargo lifting and transportation', cn: '重型货物吊装与运输' },
  'about.corporate.capacity.lifting.description': { es: 'Equipos para maniobras de izamiento y transporte de carga pesada.', en: 'Equipment for heavy cargo lifting and transportation operations.', cn: '用于重型货物吊装与运输作业的设备。' },
  'about.corporate.capacity.deployment.title': { es: 'Despliegue técnico', en: 'Technical deployment', cn: '技术部署' },
  'about.corporate.capacity.deployment.description': { es: 'Estabilización y trabajo en terrenos complejos.', en: 'Stabilization and work on complex terrain.', cn: '在复杂地形中的稳定与作业能力。' },
  'about.corporate.capacity.team.title': { es: 'Capital humano especializado', en: 'Specialized workforce', cn: '专业人才队伍' },
  'about.corporate.capacity.team.description': { es: 'Operadores y técnicos bajo estándares de seguridad.', en: 'Operators and technicians working under safety standards.', cn: '遵循安全标准的操作员和技术人员。' },
  'about.corporate.capacity.safety.title': { es: 'Cultura de prevención', en: 'Prevention culture', cn: '预防文化' },
  'about.corporate.capacity.safety.description': { es: 'Seguridad y prevención de riesgos como parte de la ejecución.', en: 'Safety and risk prevention as part of execution.', cn: '将安全和风险预防纳入作业执行过程。' },
  'about.corporate.capacity.imageAlt': { es: 'Equipo de izamiento de alta capacidad de SERLIMCA', en: 'SERLIMCA high-capacity lifting equipment', cn: 'SERLIMCA 高能力吊装设备' },

  'about.corporate.fleet.eyebrow': { es: 'Matriz de capacidad de flota', en: 'Fleet capability matrix', cn: '车队能力矩阵' },
  'about.corporate.fleet.title': { es: 'Capacidad coordinada según cada pilar operativo', en: 'Coordinated capability for each operational pillar', cn: '面向每个运营支柱的协同能力' },
  'about.corporate.fleet.description': { es: 'La flota y los recursos de apoyo se integran para acompañar las necesidades de izamiento, mantenimiento y mudanza.', en: 'The fleet and supporting resources are integrated to support lifting, maintenance, and relocation requirements.', cn: '车队与支持资源协同配置，以满足吊装、维护和搬迁需求。' },
  'about.corporate.fleet.pillarColumn': { es: 'Pilar operativo', en: 'Operational pillar', cn: '运营支柱' },
  'about.corporate.fleet.columns.cranes': { es: 'Grúas telescópicas', en: 'Telescopic cranes', cn: '伸缩臂起重机' },
  'about.corporate.fleet.columns.trailers': { es: 'Gandolas y plataformas', en: 'Lowboys and platforms', cn: '低平板与平台车' },
  'about.corporate.fleet.columns.hydraulicTrucks': { es: 'Camiones brazo hidráulico', en: 'Hydraulic-boom trucks', cn: '液压臂卡车' },
  'about.corporate.fleet.rows.lifting.label': { es: 'Izamiento y transporte de carga pesada', en: 'Heavy cargo lifting and transportation', cn: '重型货物吊装与运输' },
  'about.corporate.fleet.rows.lifting.cranes': { es: 'Maniobras de izamiento y transporte de carga pesada', en: 'Heavy cargo lifting and transportation operations', cn: '重型货物吊装与运输作业' },
  'about.corporate.fleet.rows.lifting.trailers': { es: 'Apoyo logístico', en: 'Logistics support', cn: '物流支持' },
  'about.corporate.fleet.rows.lifting.hydraulicTrucks': { es: 'Movilización auxiliar', en: 'Auxiliary mobilization', cn: '辅助调动' },
  'about.corporate.fleet.rows.maintenance.label': { es: 'Mantenimiento', en: 'Maintenance', cn: '维护' },
  'about.corporate.fleet.rows.maintenance.cranes': { es: 'Elevación de balancines', en: 'Pumpjack lifting', cn: '抽油机吊装' },
  'about.corporate.fleet.rows.maintenance.trailers': { es: 'Transporte de refacciones', en: 'Spare-parts transport', cn: '备件运输' },
  'about.corporate.fleet.rows.maintenance.hydraulicTrucks': { es: 'Logística de componentes Rotaflex', en: 'Rotaflex component logistics', cn: 'Rotaflex 部件物流' },
  'about.corporate.fleet.rows.moving.label': { es: 'Mudanza', en: 'Relocation', cn: '搬迁' },
  'about.corporate.fleet.rows.moving.cranes': { es: 'Carga y descarga en locación', en: 'On-site loading and unloading', cn: '现场装卸' },
  'about.corporate.fleet.rows.moving.trailers': { es: 'Transporte de taladros workover', en: 'Workover rig transport', cn: '修井钻机运输' },
  'about.corporate.fleet.rows.moving.hydraulicTrucks': { es: 'Escolta y carga menor', en: 'Escort and lighter cargo', cn: '护送与轻型货物' },

  'about.corporate.partners.eyebrow': { es: 'Socios de confianza', en: 'Trusted partners', cn: '信赖伙伴' },
  'about.corporate.partners.title': { es: 'Referentes que acompañan nuestra trayectoria', en: 'Organizations represented in our track record', cn: '见证我们发展历程的机构' },
  'about.corporate.partners.description': { es: 'Nombres nacionales e internacionales incluidos en nuestra presentación corporativa como respaldo a nuestra capacidad operativa y puntualidad.', en: 'National and international names included in our corporate presentation as support for our operational capability and punctuality.', cn: '企业资料中展示的国内外名称，体现了对我们运营能力和准时性的认可。' },
  'about.corporate.partners.cnpc': { es: 'CNPC', en: 'CNPC', cn: 'CNPC' },
  'about.corporate.partners.bohai': { es: 'BOHAI', en: 'BOHAI', cn: 'BOHAI' },
  'about.corporate.partners.huawei': { es: 'HUAWEY', en: 'HUAWEY', cn: 'HUAWEY' },
  'about.corporate.partners.ensing': { es: 'ENSING', en: 'ENSING', cn: 'ENSING' },
  'about.corporate.partners.sanAntonio': { es: 'SAN ANTONIO', en: 'SAN ANTONIO', cn: 'SAN ANTONIO' },
  'about.corporate.partners.venalmaQ': { es: 'VENALMAQ', en: 'VENALMAQ', cn: 'VENALMAQ' },

  'about.corporate.alignment.eyebrow': { es: 'Alineación estratégica', en: 'Strategic alignment', cn: '战略协同' },
  'about.corporate.alignment.title': { es: 'Una ruta para crecer con foco operativo', en: 'A path to grow with operational focus', cn: '以运营为重点的发展路径' },
  'about.corporate.alignment.description': { es: 'Conectamos nuestros objetivos estratégicos, operacionales y tácticos para sostener relaciones y servicios de largo plazo.', en: 'We connect strategic, operational, and tactical objectives to sustain long-term relationships and services.', cn: '我们将战略、运营和战术目标相连接，以维系长期合作关系和服务能力。' },
  'about.corporate.alignment.strategic.title': { es: 'Objetivos estratégicos', en: 'Strategic objectives', cn: '战略目标' },
  'about.corporate.alignment.strategic.description': { es: 'Consolidarnos como referente nacional y fortalecer relaciones comerciales con clientes confiables.', en: 'Consolidate our position as a national benchmark and strengthen commercial relationships with trusted clients.', cn: '巩固全国标杆地位，并加强与可信客户的商业关系。' },
  'about.corporate.alignment.operational.title': { es: 'Objetivos operacionales', en: 'Operational objectives', cn: '运营目标' },
  'about.corporate.alignment.operational.description': { es: 'Diversificar servicios para la industria con prioridad en la evolución tecnológica y técnica.', en: 'Diversify industry services with a priority on technological and technical advancement.', cn: '实现行业服务多元化，优先推动技术与专业能力提升。' },
  'about.corporate.alignment.tactical.title': { es: 'Objetivos tácticos', en: 'Tactical objectives', cn: '战术目标' },
  'about.corporate.alignment.tactical.description': { es: 'Construir relaciones comerciales estrechas y rentables con organizaciones afines a nuestros valores.', en: 'Build close, sustainable commercial relationships with organizations aligned with our values.', cn: '与认同我们价值观的组织建立紧密、可持续的商业关系。' },

  'about.corporate.cta.eyebrow': { es: 'Preparados para el próximo desafío', en: 'Ready for the next challenge', cn: '迎接下一个挑战' },
  'about.corporate.cta.title': { es: 'Llevemos su operación al siguiente nivel logístico.', en: 'Let’s take your operation to the next logistics level.', cn: '让您的运营迈向更高水平的物流能力。' },
  'about.corporate.cta.description': { es: 'Conversemos sobre el alcance técnico y operativo que necesita su próximo proyecto.', en: 'Let’s discuss the technical and operational scope your next project requires.', cn: '让我们讨论您下一个项目所需的技术与运营范围。' },
  'about.corporate.cta.button': { es: 'Contactar a SERLIMCA', en: 'Contact SERLIMCA', cn: '联系 SERLIMCA' },

  'contact.page.title': { es: 'Contacto', en: 'Corporate contact', cn: '企业联系' },
  'contact.page.highlight': { es: 'Corporativo', en: 'Corporate', cn: '企业服务' },
  'contact.page.description': { es: 'Establezca comunicación directa con nuestra unidad de gestión para requerimientos técnicos y comerciales a nivel nacional.', en: 'Contact our management team directly for nationwide technical and commercial requirements.', cn: '如有全国范围的技术和商业需求，请直接联系我们的管理团队。' },
  'contact.info.directLine': { es: 'Línea directa', en: 'Direct line', cn: '直线电话' },
  'contact.info.corporateEmail': { es: 'Correo electrónico corporativo', en: 'Corporate email', cn: '企业邮箱' },
  'contact.info.office': { es: 'Sede administrativa', en: 'Administrative office', cn: '行政办公室' },
  'contact.info.address': { es: 'Calle Codazzi, cruce con calle El Carmen, local 1, zona industrial, San José de Guanipa, estado Anzoátegui', en: 'Codazzi Street, intersection with El Carmen Street, Unit 1, Industrial Zone, San José de Guanipa, Anzoátegui State', cn: '科达齐街与埃尔卡门街交汇处，1号商铺，工业区，瓜尼帕圣何塞，安索阿特吉州' },
  'contact.info.availability': { es: 'Disponibilidad técnica 24/7', en: '24/7 technical availability', cn: '全天候技术支持' },
  'contact.form.name': { es: 'Razón social / nombre', en: 'Company name / full name', cn: '公司名称 / 姓名' },
  'contact.form.namePlaceholder': { es: 'Ingrese su identificación', en: 'Enter your name or company', cn: '请输入您的姓名或公司名称' },
  'contact.form.email': { es: 'Correo electrónico', en: 'Email address', cn: '电子邮箱' },
  'contact.form.emailPlaceholder': { es: 'name@example.com', en: 'name@example.com', cn: 'name@example.com' },
  'contact.form.phone': { es: 'Número telefónico', en: 'Phone number', cn: '电话号码' },
  'contact.form.phonePlaceholder': { es: '+58 412 1234567', en: '+1 555 123 4567', cn: '+86 138 0013 8000' },
  'contact.form.service': { es: 'Servicio de interés', en: 'Service of interest', cn: '感兴趣的服务' },
  'contact.form.message': { es: 'Especificaciones del requerimiento', en: 'Request details', cn: '需求说明' },
  'contact.form.messagePlaceholder': { es: 'Detalle los servicios solicitados', en: 'Describe the services you need', cn: '请描述您需要的服务' },
  'contact.form.privacy': { es: 'Al enviar esta solicitud, sus datos serán procesados bajo estrictos protocolos de seguridad industrial y confidencialidad.', en: 'By sending this request, your information will be processed under strict industrial security and confidentiality protocols.', cn: '提交此申请即表示您的信息将按照严格的工业安全和保密协议进行处理。' },
  'contact.form.submit': { es: 'Enviar solicitud', en: 'Send request', cn: '提交申请' },
  'contact.form.sending': { es: 'Enviando...', en: 'Sending...', cn: '正在发送…' },
  'contact.form.success': { es: 'Solicitud enviada correctamente.', en: 'Your request was sent successfully.', cn: '您的申请已成功发送。' },
  'contact.form.error': { es: 'No pudimos enviar la solicitud. Intentá nuevamente.', en: 'We could not send your request. Please try again.', cn: '无法发送您的申请，请重试。' },
  'contact.form.phoneFallback': { es: 'No indicado', en: 'Not provided', cn: '未提供' },
  'contact.service.transport': { es: 'Izamiento y transporte de carga pesada', en: 'Heavy cargo lifting and transportation', cn: '重型货物吊装与运输' },
  'contact.service.maintenance': { es: 'Mantenimiento y equipos', en: 'Maintenance and equipment', cn: '维护与设备' },
  'contact.service.infrastructure': { es: 'Proyectos de infraestructura', en: 'Infrastructure projects', cn: '基础设施项目' },
  'contact.service.support': { es: 'Soporte operativo', en: 'Operational support', cn: '运营支持' },

  'contactCta.badge': { es: 'Soporte industrial activo', en: 'Active industrial support', cn: '工业支持在线' },
  'contactCta.titleBefore': { es: 'Impulse su', en: 'Drive your', cn: '推动您的' },
  'contactCta.titleHighlight': { es: 'operación', en: 'operation', cn: '运营' },
  'contactCta.titleAfter': { es: 'hoy', en: 'today', cn: '今天' },
  'contactCta.description': { es: 'No deje su logística al azar. Nuestro equipo de ingenieros y especialistas está listo para desplegar soluciones en tiempo récord.', en: 'Do not leave your logistics to chance. Our engineers and specialists are ready to deploy solutions in record time.', cn: '不要让物流靠运气。我们的工程师和专家团队随时准备以最快速度部署解决方案。' },
  'contactCta.benefit.availability': { es: 'Disponibilidad nacional 24/7', en: 'Nationwide availability 24/7', cn: '全国全天候服务' },
  'contactCta.benefit.certified': { es: 'Personal certificado', en: 'Certified personnel', cn: '认证人员' },
  'contactCta.benefit.cargo': { es: 'Gestión de carga crítica', en: 'Critical cargo management', cn: '关键货物管理' },
  'contactCta.quote': { es: 'Iniciar cotización', en: 'Start a quote', cn: '开始询价' },
  'contactCta.whatsapp': { es: 'WhatsApp directo', en: 'WhatsApp direct', cn: 'WhatsApp 直连' },
  'contactCta.directLine': { es: 'Línea directa', en: 'Direct line', cn: '直线电话' },
  'contactCta.directLineSub': { es: 'Atención técnica inmediata', en: 'Immediate technical support', cn: '即时技术支持' },
  'contactCta.corporateEmail': { es: 'Correo electrónico corporativo', en: 'Corporate email', cn: '企业邮箱' },
  'contactCta.corporateEmailSub': { es: 'Solicitudes de licitación', en: 'Tender requests', cn: '招标咨询' },
  'contactCta.operationCenter': { es: 'Centro de operaciones', en: 'Operations center', cn: '运营中心' },
  'contactCta.hours': { es: 'Lunes a viernes: 08:00 - 18:00', en: 'Monday to Friday: 08:00 - 18:00', cn: '周一至周五：08:00 - 18:00' },
  'contactCta.emergency': { es: 'Emergencias: disponibilidad 24/7', en: 'Emergency: availability 24/7', cn: '紧急服务：全天候响应' },
  'contactCta.response': { es: 'Respuesta', en: 'Response', cn: '响应时间' },
  'contactCta.projects': { es: 'Proyectos', en: 'Projects', cn: '项目' },
  'contactCta.confidence': { es: 'Confianza', en: 'Trust', cn: '信赖' },

  'footer.description': { es: 'Soluciones industriales y logísticas de excelencia. Comprometidos con la calidad y el servicio profesional en toda Venezuela.', en: 'Outstanding industrial and logistics solutions. Committed to quality and professional service throughout Venezuela.', cn: '提供卓越的工业和物流解决方案。我们致力于在委内瑞拉各地提供优质、专业的服务。' },
  'footer.navigation': { es: 'Navegación', en: 'Navigation', cn: '导航' },
  'footer.specialties': { es: 'Especialidades', en: 'Specialties', cn: '专业领域' },
  'footer.contact': { es: 'Contacto', en: 'Contact', cn: '联系信息' },
  'footer.callUs': { es: 'Llámanos', en: 'Call us', cn: '致电我们' },
  'footer.writeUs': { es: 'Escríbenos', en: 'Email us', cn: '给我们发邮件' },
  'footer.rights': { es: 'Todos los derechos reservados.', en: 'All rights reserved.', cn: '版权所有。' },
  'footer.privacy': { es: 'Privacidad', en: 'Privacy', cn: '隐私政策' },
  'footer.terms': { es: 'Términos', en: 'Terms', cn: '服务条款' },
  'footer.service.transport': { es: 'Izamiento y transporte de carga pesada', en: 'Heavy cargo lifting and transportation', cn: '重型货物吊装与运输' },
  'footer.service.maintenance': { es: 'Mantenimiento industrial', en: 'Industrial maintenance', cn: '工业维护' },
  'footer.service.logistics': { es: 'Logística integral', en: 'Integrated logistics', cn: '综合物流' },
  'footer.service.consulting': { es: 'Consultoría', en: 'Consulting', cn: '咨询服务' },

  'marquee.text': { es: 'CALIDAD ~ CONFIANZA ~ EXPERIENCIA ~ INNOVACIÓN ~ COMPROMISO ~ EXCELENCIA ~', en: 'QUALITY ~ TRUST ~ EXPERIENCE ~ INNOVATION ~ COMMITMENT ~ EXCELLENCE ~', cn: '质量 ~ 信赖 ~ 经验 ~ 创新 ~ 承诺 ~ 卓越 ~' },
  'scrollToTop': { es: 'Volver arriba', en: 'Back to top', cn: '返回顶部' },
  'socialMedia': { es: 'redes sociales', en: 'social media', cn: '社交媒体' },
  'notFound.title': { es: 'Página no encontrada', en: 'Page not found', cn: '页面未找到' },
  'notFound.description': { es: 'La página que buscás no existe o fue movida.', en: 'The page you are looking for does not exist or was moved.', cn: '您查找的页面不存在或已被移动。' },
  'notFound.action': { es: 'Volver al inicio', en: 'Back to home', cn: '返回首页' },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('es');

  const t = useCallback((key, values = {}) => {
    const translation = translations[key]?.[language] ?? translations[key]?.es ?? key;
    return Object.entries(values).reduce(
      (result, [name, value]) => result.replaceAll(`{{${name}}}`, value),
      translation,
    );
  }, [language]);

  useEffect(() => {
    document.documentElement.lang = language === 'cn' ? 'zh-CN' : language;
    document.title = translations['meta.title']?.[language] ?? translations['meta.title'].es;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
